language: go
sudo: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/tmp/codecov
    - $HOME/tmp/gotestsum

go:
    - 1.13.x

env:
  - OS=linux ARCH=amd64 TMP_DIR=$HOME/tmp

install: sudo make codecov.install gotestsum.install

script: make ci

after_success: make codecov.push

notifications:
    email:
        on_success: change
        on_failure: always
